Repository kaal-coder/hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#187 Reverse linked-list code resolved#150
  Coding/reverse linked list
  Python Projects/Virtual-Assistant-Alexa-main/Virtual-Assistant-Alexa-main/Alexa - Virtual Assistant/PyWhatKit_DB.txt
Labels: hacktoberfest

#219 Added QR-Generator Project
  Full Stack Projects/QR-Generator/package-lock.json
  Full Stack Projects/QR-Generator/package.json
  Full Stack Projects/QR-Generator/public/background.jpg
  Full Stack Projects/QR-Generator/qr-images/alt.jpg
  Full Stack Projects/QR-Generator/qr-images/qr_img.png
  Full Stack Projects/QR-Generator/solution.js
  Full Stack Projects/QR-Generator/urls/URL.txt
  Full Stack Projects/QR-Generator/views/form.ejs
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#257 Menu Display app using html, css, js
  Fronted Projects/Restaurant Menu Display/food1.jpg
  Fronted Projects/Restaurant Menu Display/food10.jpg
  Fronted Projects/Restaurant Menu Display/food11.jpg
  Fronted Projects/Restaurant Menu Display/food12.jpg
  Fronted Projects/Restaurant Menu Display/food2.jpg
  Fronted Projects/Restaurant Menu Display/food3.jpg
  Fronted Projects/Restaurant Menu Display/food4.jpg
  Fronted Projects/Restaurant Menu Display/food5.jpg
  Fronted Projects/Restaurant Menu Display/food6.jpg
  Fronted Projects/Restaurant Menu Display/food7.jpg
  Fronted Projects/Restaurant Menu Display/food8.jpg
  Fronted Projects/Restaurant Menu Display/food9.jpg
  Fronted Projects/Restaurant Menu Display/logo.png
  Fronted Projects/Restaurant Menu Display/menu.css
  Fronted Projects/Restaurant Menu Display/menu.html
  Fronted Projects/Restaurant Menu Display/menu.js
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#262 Image search engine added
  Fronted Projects/Image Search Engine/index.html
  Fronted Projects/Image Search Engine/script.js
  Fronted Projects/Image Search Engine/stye.css
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#259 added a console based cricket game
  Python Projects/ cricGame/cricGamereadme.md
  Python Projects/ cricGame/cricgame.py
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#271 Added programs for Operating systems
  Operating Systems/CPU Scheduling Algorithms/FirstComeFirstServe.c
  Operating Systems/CPU Scheduling Algorithms/Priority.c
  Operating Systems/CPU Scheduling Algorithms/RoundRobin.c
  Operating Systems/CPU Scheduling Algorithms/ShortestJobFirst.c
  Operating Systems/Memory Allocation Methods/BestFit.c
  Operating Systems/Memory Allocation Methods/FirstFit.c
  Operating Systems/Memory Allocation Methods/WorstFit.c
  Operating Systems/Page Replacement Algorithms/FirstInFirstOut.c
  Operating Systems/Page Replacement Algorithms/LeastRecentlyUsed.c
  Operating Systems/Page Replacement Algorithms/Optimal.c
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#270 feat(app): add tinDog-canine-connection-app
  Fronted Projects/tinDog - Canine Connection App/README.md
  Fronted Projects/tinDog - Canine Connection App/css/styles.css
  Fronted Projects/tinDog - Canine Connection App/images/1.png
  Fronted Projects/tinDog - Canine Connection App/images/2.png
  Fronted Projects/tinDog - Canine Connection App/images/3.png
  Fronted Projects/tinDog - Canine Connection App/images/bizinsider.png
  Fronted Projects/tinDog - Canine Connection App/images/dog-favicon.png
  Fronted Projects/tinDog - Canine Connection App/images/dog-img.jpg
  Fronted Projects/tinDog - Canine Connection App/images/iphone6--2.png
  Fronted Projects/tinDog - Canine Connection App/images/iphone6.png
  Fronted Projects/tinDog - Canine Connection App/images/lady-img.jpg
  Fronted Projects/tinDog - Canine Connection App/images/mashable.png
  Fronted Projects/tinDog - Canine Connection App/images/tc-logo.png
  Fronted Projects/tinDog - Canine Connection App/images/tnw.png
  Fronted Projects/tinDog - Canine Connection App/index.html
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#268 [JAVA] maze solver
  Coding/Java/Maze.java
  Coding/Java/Sudoko.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#267 [JAVA] sudoku solver
  Coding/Java/Maze.java
  Coding/Java/Sudoko.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#279 Hacktoberfest Contributed to Repository
  Fronted Projects/Documentation-page.html
  Fronted Projects/HtmlCanvas.html
  Fronted Projects/flex-panel.html
  ML Project/Driver Code.ipynb
  ML Project/Gesture Detection.ipynb
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#292 Added a new program in c++
  Coding/C++/merge_k_sorted_linkedlists.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#291 added a project of mine - have a follow
  Python Projects/Roulette/Project.py
  Python Projects/Roulette/roulette.png
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#287 add a blog/article about java language
  Blogs/Java Programming Language.pdf
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#286 Create Animated Buttons in HTML
  Coding/HTML/Animated Buttons in HTML
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#214 Added Linux Commands blog
  Blogs/Linux Commands.txt
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#216 Create terraform-linuxvm
  .vscode/terraform-linuxvm
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#217 Advice Generator App
  Fronted Projects/Advice generator app/app.js
  Fronted Projects/Advice generator app/images/favicon-32x32.png
  Fronted Projects/Advice generator app/images/icon-dice.svg
  Fronted Projects/Advice generator app/images/pattern-divider-desktop.svg
  Fronted Projects/Advice generator app/images/pattern-divider-mobile.svg
  Fronted Projects/Advice generator app/index.html
  Fronted Projects/Advice generator app/style.css
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#221 Create bfs_traversal.cpp
  bfs_traversal.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#225 Create NumbertoRoman.cpp
  Coding/NumbertoRoman.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#226 Added Hangman game with anime character names
  Python Projects/Hangman Game/Hangman.py
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#231 Create bubble.cpp
  bubble.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#211 ImageDataGenerator
  ML Project/ImageDataGenerator
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#234 Add sieve_of_eratosthenes.cpp
  Coding/sieve_of_eratosthenes.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#235 Update index.html
  Fronted Projects/Analog Clock/index.html
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#344 added flames game
  Coding/C++/flames-game.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#349 Huffman Algorithm Implementation in C++.
  Coding/C++/Huffman_Coding/Huffman.cpp
  Coding/C++/Huffman_Coding/Huffman.hpp
  Coding/C++/Huffman_Coding/commands_to_run.txt
  Coding/C++/Huffman_Coding/compressed.txt
  Coding/C++/Huffman_Coding/decompressed.txt
  Coding/C++/Huffman_Coding/main.exe
  Coding/C++/Huffman_Coding/sample.txt
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#352 functional calculator using Html,Css,JavaScript
  Fronted Projects/Working_Calculator/calculate.js
  Fronted Projects/Working_Calculator/index.html
  Fronted Projects/Working_Calculator/styles.css
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#365 Point of Sale App
  Fronted Projects/POS/.gitignore
  Fronted Projects/POS/.vscode/extensions.json
  Fronted Projects/POS/README.md
  Fronted Projects/POS/index.html
  Fronted Projects/POS/package-lock.json
  Fronted Projects/POS/package.json
  Fronted Projects/POS/public/vite.svg
  Fronted Projects/POS/src/App.vue
  Fronted Projects/POS/src/assets/vue.svg
  Fronted Projects/POS/src/components/PosApp.vue
  Fronted Projects/POS/src/main.ts
  Fronted Projects/POS/src/style.css
  Fronted Projects/POS/src/vite-env.d.ts
  Fronted Projects/POS/tsconfig.json
  Fronted Projects/POS/tsconfig.node.json
  Fronted Projects/POS/vite.config.ts
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#408 Added BackEnd Developer Roadmap #303
  Blogs/social media blog.html
  Roadmap/Backend devoloper.txt
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#407 whole_number.cpp
  Coding/C++/whole_number.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#405 Contributing in No code domain:Roadmaps,UI design
  .idea/.gitignore
  .idea/hacktoberfest2023.iml
  .idea/libraries/Dart_SDK.xml
  .idea/modules.xml
  .idea/vcs.xml
  Roadmap/blockchain roadmap.pdf
  Roadmap/devops roadmap.pdf
  Roadmap/sql's roadmap.pdf
  UI- UX Projects  Design/landingUI.png
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#404 Add script to perform weighted probabilities
  Python Projects/Weighted Distribution/main.py
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#403 added Dijkstra's Algorithm
  Coding/C++/DijkstraAlgorithm.cpp
  Coding/C++/topologicalsort.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#401 Added a new web-based project and some Java programs
  Coding/Java/ArrayListIterator.java
  Coding/Java/MatrixTranspose.java
  Coding/Java/StringWordCountHashmap.java
  Coding/Java/StudentCoursesList.java
  Full Stack Projects/Attendance_Management_System/194006_Project_Synopsis_PHPP.docx
  Full Stack Projects/Attendance_Management_System/194006_Project_Synopsis_PHPP.pdf
  Full Stack Projects/Attendance_Management_System/AddStudent.php
  Full Stack Projects/Attendance_Management_System/AddStudent.txt
  Full Stack Projects/Attendance_Management_System/AttendanceManagementSystem.php
  Full Stack Projects/Attendance_Management_System/AttendanceManagementSystem.txt
  Full Stack Projects/Attendance_Management_System/BaseMenu.php
  Full Stack Projects/Attendance_Management_System/BaseMenu.txt
  Full Stack Projects/Attendance_Management_System/DataBase.php
  Full Stack Projects/Attendance_Management_System/DataBase.txt
  Full Stack Projects/Attendance_Management_System/HomePage.php
  Full Stack Projects/Attendance_Management_System/HomePage.txt
  Full Stack Projects/Attendance_Management_System/PresentAbsent.php
  Full Stack Projects/Attendance_Management_System/PresentAbsent.txt
  Full Stack Projects/Attendance_Management_System/README.txt
  Full Stack Projects/Attendance_Management_System/ViewAttendance.php
  Full Stack Projects/Attendance_Management_System/ViewAttendance.txt
  Full Stack Projects/Attendance_Management_System/ViewStudent.php
  Full Stack Projects/Attendance_Management_System/ViewStudent.txt
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#399 Create binary.py
  binary.py
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#397 Create avl_adt.cpp
  Coding/C++/avl_adt.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#393 Rain Prediction Model
  ML Project/Rain_Prediction using PyCaret.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#392 Added a full fledged roadmap to become a proficient backend developer.
  Roadmap/BackendDevelopementRoadmap.txt
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#391 Create blog about problem faced by AI companies
  Blogs/blog about problem faced by AI companies
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#390 MathematicalandTrignometricmethodsinPython.txt
  MathrmaticalandTrignometricmethodsinPython.txt
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#389 Added an ML project
  ML Project/EmotionsDetector.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#388 Create MovieRecommendationSystemMLProject.ipynb
  MovieRecommendationSystemMLProject.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#386 Create BoyerMooreVoting.java
  Coding/Java/BoyerMooreVoting.java
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#385 Create linear search.java
  Coding/Java/linear search.java
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#384 Book recommendation system
  ML Project/.gitignore
  ML Project/LICENSE
  ML Project/README.md
  ML Project/app.py
  ML Project/books.csv
  ML Project/dfbeforeprocess.csv
  ML Project/final.csv
  ML Project/main.ipynb
  ML Project/requirements.txt
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#383 Added UI designer roadmap(
  Roadmap/UI Designer Roadmap.pdf
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#380 Implemented a random password generator in Python for the Hackertuber…
  Python Projects/Password Generate/Password_generator.py
Labels: enhancement, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#377 Add files via upload
  Fronted Projects/Math Academy.html
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#375 Create GCD.java
  Roadmap/GCD.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#373 Created LibraryManagementSystem
  Coding/C++/LibraryManagementSystem /PASSWORD.txt
  Coding/C++/LibraryManagementSystem /librarymanagementsystem.cpp
  Coding/C++/LibraryManagementSystem/librarymanagementsystem.exe
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#371 Create CyberbookStore.html
  Coding/HTML/CyberbookStore.html
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#370 Create listcomprehension.py
  listcomprehension.py
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#369 Create whatsapp-monitor.py
  Python Projects/whatsapp_monitor/whatsapp-monitor.py
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#367 Create Tim_sort_Algo_Atul.cpp
  Coding/C++/Tim_sort_Algo_Atul.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#364 Create Reverse_a_Number.java
  Coding/Java/Reverse_a_Number.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#362 Frontend project added
  Fronted Projects/Profile Page/readme.md
  Fronted Projects/Profile Page/screenshot.png
  Fronted Projects/Profile Page/soham.html
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#357 Create floor.java
  Coding/Java/floor.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#353 Create ParanthesesChecker.c
  ParanthesesChecker.c
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#347 Create Constrained_Subsequence_Sum_LeetCode.java
  Constrained_Subsequence_Sum_LeetCode.java
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#427 Create Power Set in Lexicographic order.cpp
  Coding/C++/Power Set in Lexicographic order.cpp
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted
